// ignore_for_file: equal_keys_in_map

import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'Log In': 'Log In',
      'Become a Driver?': 'Become a Driver?',
      'States': 'States',
      'Breakdown': 'Breakdown',
      'Profile': 'Profile',
      'Rating Score': 'Rating Score',
      'Invite Friends to Earn Points': 'Invite Friends to Earn Points',
      'Need a Support': 'Need a Support',
      'Feedback Us': 'Feedback Us',
      'Language': 'Language',
      'Logout': 'Logout',
      'verify phone Number': 'verify phone Number',
      'Next': 'Next',
      'Enter code': 'Enter code',
      'Resend Code': 'Resend Code',
      'Enter your mobile phone number to receive one-time password (OTP)':
      'Enter your mobile phone number to receive one-time password (OTP)',
      'Name': 'Name',
      'sex': 'sex',
      'M': 'M',
      'F': 'F',
      'Birth Year': 'Birth Year',
      'Mobile Phone': 'Mobile Phone',
      'Enter your phone number': 'Enter your phone number',
      'Choose your vehicle': 'Choose your vehicle',
      'Bike': 'Bike',
      'Motor': 'Motor',
      'Rickshaw': 'Rickshaw',
      'Where do u live': 'Where do u live',
      'District': 'District',
      'Commune': 'Commune',
      'Your time available': 'Your time available',
      'Morning': 'Morning',
      'Afternoon': 'Afternoon',
      'Evening': 'Evening',
      'Take your ID card photo': 'Take your ID card photo',
      'Referral code if have': 'Referral code if have',
      'Enter code': 'Enter code',
      'Submit': 'Submit',
      'Thank You': 'Thank You',
      'You are now submitted': 'You are now submitted',
      'You have successfully submitted a request to be our driver partner. you will be contacted by our team very soon ':
      'You have successfully submitted a request to be our driver partner. you will be contacted by our team very soon ',
      'Got it ': 'Got it ',
      'fail': 'fail',
      'Your Phone Number is already to register! Please try to login! Thanks.':
      'Your Phone Number is already to register! Please try to login! Thanks.',
      'Home': 'Home',
      'Report': 'Report',
      'Order': 'Order',
      'Account': 'Account',
      'Trip': 'Trip',
      'Point': 'Point',
      'Distance': 'Distance',
      'Customer': 'Customer',
      'Merchant': 'Merchant',
      'Breakdown': 'Breakdown',
      'Net delivery fee': 'Net delivery fee',
      'Bonus': 'Bonus',
      ' Total Earning: ': ' Total Earning: ',
      'Total Earning': 'Total Earning',
      'Total Earning': 'Total Earning:',
      'Notification': 'Notification',
      'Order Details': 'Order Details',
      'Delivered': 'Delivered',
      'Canceled': 'Canceled',
      'Order ID': 'Order ID',
      'Delivered successfully to': 'Delivered successfully to',
      'Reject': 'Reject',
      'Accept': 'Accept',
      'On the way to pickup': 'On the way to pickup',
      'Customer Details': 'Subtotal',
      'Subtotal': 'Subtotal',
      'choose one of problems you are facing now':
      'choose one of problems you are facing now',
      'Customer is not reachable': 'Customer is not reachable',
      'Customer has just cancel': 'Customer has just cancel',
      'Read all': 'Read all',
      'Big Discount': 'Big Discount',
      'view location': 'view location',
      'Delete': 'Delete',
      'Do you want to deleted your Notification':
      'Do you want to deleted your Notification',
      'Thank you': 'Thank you',
      'Other': 'Other',
      'Setting': 'Setting',
      'Edit Profile': 'Edit Profile',
      'Rating Score': 'Rating Score',
      'Invite Friends to Eam points': 'Invite Friends to Eam points',
      'Need a Support': 'Need a Support',
      'Feedback Us': 'Feedback Us',
      'language': 'language',
      'Start Date': 'Start Date',
      'End Date': 'End Date',
      'Sun': 'Sun',
      'Mon': 'Mon',
      'Tue': 'Tue',
      'Wed': 'Wed',
      'Thu': 'Thu',
      'Fri': 'Fri',
      'Sat': 'Sat',
      'Change': 'Change',
      'Recent Feedback': 'Recent Feedback',
      'You did a great service': 'You did a great service',
      'keep your work': 'keep your work',
      'Satisfaction Detail': 'Satisfaction Detail',
      'All time ratings': 'All time ratings',
      'Fitter by Date:': 'Fitter by Date:',
      'to': 'to',
      'Total Satisfaction Score': 'Total Satisfaction Score',
      'Aim': 'Aim',
      'Total Points': 'Total Points',
      'Invite a friend, Get 5 points with terms:':
      'Invite a friend, Get 5 points with terms:',
      'Download a Driver App.': 'Download a Driver App.',
      'Apply for a driver by using your referral code: ':
      'Apply for a driver by using your referral code: ',
      'The driver is approved and starting the driving job.':
      'The driver is approved and starting the driving job.',
    },
    'kh_KH': {
      'Log In': 'ចូល',
      'Become a Driver?': 'ក្លាយជាអ្នកបើកបរ?',
      'States': 'ស្ថិតិ',
      'Breakdown': 'ពត៌មានបន្ថែម',
      'Profile': 'ប្រូហ្វាល',
      'Rating Score': 'ពិន្ទុវាយតម្លៃ',
      'Invite Friends to Earn Points': 'ណែនាំមិត្តភក្តិដើម្បីទទួលបានពិន្ទុ',
      'Need a Support': 'ត្រូវការជំនួយ',
      'Feedback Us': 'វាយតម្លៃយើង',
      'Language': 'កំណត់ភាសា',
      'Logout': 'ចាកចេញ',
      'verify phone Number': 'ផ្ទៀងផ្ទាត់លេខទូរស័ព្ទ',
      'Next': 'បន្ទាប់',
      'Enter code': 'បញ្ជូលលេខកូដ',
      'Resend Code': 'ផ្ញើលេខកូដម្តងទៀត',
      'Enter your mobile phone number to receive one-time password (OTP)':
      'បញ្ជូលលេខទូរស័ព្ទដើម្បីទទួលលេខកូដសម្ងាត់៦ខ្ទង់',
      'Name': 'ឈ្មោះ',
      'sex': 'ភេទ',
      'M': 'ប្រុស',
      'F': 'ស្រី',
      'Birth Year': 'ឆ្នាំកំណើត',
      'Mobile Phone': 'លេខទូរស័ព្ទ',
      'Enter your phone number': 'បញ្ជូលលេខទូរស័ព្ទ',
      'Choose your vehicle': 'ជ្រើសរើសមធ្យោបាយដឺកជញ្ជួន',
      'Bike': 'កង់',
      'Motor': 'ម៉ូតូ',
      'Rickshaw': 'ម៉ូតូកង់បី',
      'Where do u live': 'ទីកន្លែងរស់នៅ',
      'District': 'ខណ្ឌ',
      'Commune': 'ឃុំ',
      'Your time available': 'វេនធ្វើការ',
      'Morning': 'ព្រឹក',
      'Afternoon': 'រសៀល',
      'Evening': 'ល្ងាច',
      'Take your ID card photo': 'ថតរូបអត្តសញ្ញាណប័ណ្ឌរបស់អ្នក',
      'Referral code if have': 'កូដអ្នកណែនាំ',
      'Enter code': 'បញ្ជូលលេខកូដ',
      'Submit': 'ដាក់ស្នើ',
      'Thank You': 'សូមអរគុណ',
      'You are now submitted': 'អ្នកបានធ្វើការស្នើសុំ',
      'You have successfully submitted a request to be our driver partner. you will be contacted by our team very soon ':
      'អ្នកបានជោគជ័យក្នងការស្នើសុំំធ្វើជាដៃគូរសហការដឹកជញ្ជូនរបស់យើង ពួកយើងនិងធ្វើការទាក់ទងអ្នកក្នងពេលឆាប់ៗនេះ',
      'Got it ': 'ការស្នើរបស់អ្នកជោគជ័យ',
      'fail': 'បរាជ័យ',
      'Your Phone Number is already to register! Please try to login! Thanks.':
      'លេខទូរស័ព្ទរបស់អ្នកបានធ្វើការចុះឈ្មៅះរួចរាល់! សូមព្យាយាមម្តងទៀត! អរគុណ',
      'Home': 'ទំព័រដើម',
      'Report': 'របាយការណ៍',
      'Order': 'ការបញ្ជាទិញ',
      'Account': 'គណនី',
      'Trip': 'ចំនួនដឺក',
      'Point': 'ពិន្ទុ',
      'Distance': 'ចម្ងាយដឹក',
      'Customer': 'អតិថិជន',
      'Merchant': 'ហាង',
      'Breakdown': 'ពត៏មានបន្ថែម',
      'Net delivery fee': 'ថ្លៃដឺក',
      'Bonus': 'ប្រាក់បន្ថែម',
      ' Total Earning: ': 'កម្រៃទទួលបានសរុប: ',
      'Total Earning': 'កម្រៃទទួលបានសរុប',
      'Total Earning:': 'កម្រៃទទួលបានសរុប:',
      'Notification': 'ដណឺង',
      'Order Details': 'ពត៏មានការបញ្ជាទិញលំអិត',
      'Delivered': 'បានដឺកជោកជ័យ',
      'Canceled': 'បញ្ឈប់ការបញ្ជាទិញ',
      'Order ID': 'លេខរាងការកម្មង់',
      'Delivered successfully to': 'ដឹកជញ្ជូនបានជោគជ័យទៅកាន់',
      'Reject': 'មិនទទួលយក',
      'Accept': 'ទទួលយក',
      'On the way to pickup': 'នៅតាមផ្លូវទៅទទួលអីវាន់',
      'Customer Details': 'លម្អិត',
      'Subtotal': 'តម្លៃសរុប',
      'choose one of problems you are facing now':
      'ជ្រើសរើសបញ្ហាដែលអ្នកបានកំពុងជួប',
      'Customer is not reachable': 'អតិថិជនមិនអាចទាក់ទងបាន',
      'Customer has just cancel': 'អតិថិជនទើបតែបញ្ឈប់ការបញ្ជាទិញ',
      'Read all': 'អានទាំងអស់',
      'Big Discount': 'ប្រូមូសិនពិសេស',
      'view location': 'បង្ហាញទីតាំង',
      'Delete': 'លុបចោល',
      'Do you want to deleted your Notification':
      'តើអ្នកចង់លុបចោលការបញ្ជាទិញ',
      'Thank you': 'អរគុណ',
      'Other': 'ផ្សេងៗ',
      'Edit Profile': 'កែប្រែប្រូហ្វាល់',
      'Setting': 'ការកំណត់',
      'Rating Score': 'ពិន្ទុវាយតម្លៃ',
      'Invite Friends to Eam points': 'ណែនាំមិត្តភក្តិដើម្បីទទួលបានពិន្ទុ',
      'Need a Support': 'ត្រូវការជំនួយ',
      'Feedback Us': 'មតិយោបល់',
      'language': 'ភាសា',
      'Start Date': 'ចាប់ពី',
      'End Date': 'ដល់',
      'Sun': 'អាទិត្យ',
      'Mon': 'ចន្ទ',
      'Tue': 'អង្គារ',
      'Wed': 'ពុធ',
      'Thu': 'ព្រហ',
      'Fri': 'សុក្រ',
      'Sat': 'សៅរ៍',
      'Change': 'ផ្លាស់ប្តួរ',
      'Recent Feedback': 'ការរិះគុណពីមុន',
      'You did a great service': '',
      'keep your work': '',
      'Satisfaction Detail': 'ពត៌មានពិន្ទុលម្អិត',
      'All time ratings': 'ពិន្ទុទាំងអស់',
      'Fitter by Date:': 'ជ្រើសរើសថ្ងៃ:',
      'to': 'ទៅកាន់',
      'Total Satisfaction Score': 'ពិន្ទុសរុប',
      'Aim': 'ស្ថានភាព',
      'Total Points': 'ពិន្ទុ',
      'Invite a friend, Get 5 points with terms:':
      'ណែនាំមិត្តភ័ក្រ អ្នកនឹងទទួលបាន 5 ពិន្ទុបន្ថែមក្នុងលក្ខខណ្ឌដូចខាងក្រោម:',
      'Download a Driver App.': 'ទាញយកកម្មវិធី អ្នកដឹកជញ្ជូន',
      'Apply for a driver by using your referral code: ':
      'ដាក់ពាក្យស្នើមកខាងក្រុមហ៊ុន ដោយប្រើលេខកូដ: ',
      'The driver is approved and starting the driving job.':
      'ក្លាយជាអ្នកដឹកជញ្ជូនពេញសិទ្ធិ',
    },
  };
}